This resolves an issue where a random TCP client goes away before a response is sent from the server. The resulting exception was not handled, and would cause node.js to crash.
The log file would show this message as a result:
node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: write ECONNRESET
    at errnoException (net.js:642:11)
    at Object.afterWrite [as oncomplete] (net.js:480:18)